#kia
vehicle_internal_state_topic: "/imu/velocity"
gps_topic: "/imu/nav_sat_fix" #"/ublox_gps/fix"
imu_topic: "/imu/data"
publish_topic: "VehStEstimatorDataNew"

#carla
#vehicle_internal_state_topic: "/carla/ego_vehicle/speedometer"
#gps_topic: "/ublox_gps/fix"
#imu_topic: /carla/ego_vehicle/imu
#publish_topic: "VehStEstimatorDataNew"
